name: Functionnal Project Tests

on: [push, pull_request]

jobs:
  TestProject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9.7

      - name: Install Depedencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip

      - name: Launch Subject Tests
        run: |
          ./304pacman maps/map01 '@' ' ' >> testResult
          ./304pacman maps/map_big_with_walls '@' ' ' >> testResult
          ./304pacman maps/map_closed '@' ' ' >> testResult
          ./304pacman maps/map_closed_2 '@' ' ' >> testResult

      - name: Launch Error Handling Test 1
        continue-on-error: true
        run: ./304pacman maps/map01 '0' '*' >> testResult

      - name: Launch Error Handling Test 2
        continue-on-error: true
        run: ./304pacman maps/map01 '*' '0' >> testResult

      - name: Launch Error Handling Test 3
        continue-on-error: true
        run: ./304pacman maps/map01 '*' '*' >> testResult

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./testResult