name: ProjectTests

on: [push, pull_request]

jobs:
  TestProject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9.7

      - name: Install Depedencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip

      - name: Launch Tests
        continue-on-error: true
        run: |
          ./304pacman map01 '*' 'M' >> testResult
          ./304pacman map01 '0' '*' >> testResult
          ./304pacman map01 '*' '0' >> testResult
          ./304pacman map01 '*' '*' >> testResult

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./testResult